import { constant } from "@/lib/constant";

// roles.ts
export const ROLES = {
  ADMIN: "Super Admin",
  REGIONAL_ADMIN: "Regional Admin",
  SEO: "SEO Agent",
  PARTNER: "Partner",
  DISPATCHER: "Dispatcher",
} as const;

// Permission to Route mapping - This maps backend permissions to frontend routes
export const PERMISSION_TO_ROUTE_MAPPING: Record<string, string[]> = {
  // User Management
  manageUsers: [
    constant.ROUTING_URLS.USERS,
    constant.ROUTING_URLS.CREATE_USERS,
    constant.ROUTING_URLS.EDIT_USERS,
    constant.ROUTING_URLS.VIEW_USERS,
  ],

  // Staff Management
  manageStaffMembers: [
    constant.ROUTING_URLS.STAFF_MEMBERS,
    constant.ROUTING_URLS.CREATE_STAFF_MEMBERS,
    constant.ROUTING_URLS.EDIT_STAFF_MEMBERS,
  ],

  // Permission Management
  managePermissions: [constant.ROUTING_URLS.SETTINGS],

  // Regional Management
  managePartners: [
    constant.ROUTING_URLS.PARTNER,
    constant.ROUTING_URLS.CREATE_PARTNER,
    constant.ROUTING_URLS.EDIT_PARTNER,
    constant.ROUTING_URLS.VIEW_PARTNER,
  ],

  manageChauffeurs: [
    constant.ROUTING_URLS.CHAUFFEUR,
    constant.ROUTING_URLS.VIEW_CHAUFFEUR,
  ],

  managePartnerChauffeurs: [
    constant.ROUTING_URLS.CHAUFFEUR,
    constant.ROUTING_URLS.CREATE_CHAUFFEUR,
    constant.ROUTING_URLS.EDIT_CHAUFFEUR,
    constant.ROUTING_URLS.VIEW_CHAUFFEUR,
  ],

  manageRegions: [
    constant.ROUTING_URLS.REGION,
    constant.ROUTING_URLS.CREATE_REGION,
    constant.ROUTING_URLS.EDIT_REGION,
  ],

  manageReports: [
    constant.ROUTING_URLS.REPORTS,
    constant.ROUTING_URLS.DASHBOARD,
  ],

  // Content Management
  manageContentManagement: [
    constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES,
    constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT,
    constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT,
    constant.ROUTING_URLS.FAQ,
    constant.ROUTING_URLS.CREATE_FAQ,
    constant.ROUTING_URLS.EDIT_FAQ,
  ],

  manageSeo: [constant.ROUTING_URLS.SEO, constant.ROUTING_URLS.REPORTS],

  manageNews: [
    constant.ROUTING_URLS.NEWS,
    constant.ROUTING_URLS.CREATE_NEWS,
    constant.ROUTING_URLS.EDIT_NEWS,
  ],

  manageTestimonials: [
    constant.ROUTING_URLS.TESTIMONIALS,
    constant.ROUTING_URLS.CREATE_TESTIMONIALS,
    constant.ROUTING_URLS.EDIT_TESTIMONIALS,
  ],

  manageBlogs: [
    constant.ROUTING_URLS.BLOG_POSTS,
    constant.ROUTING_URLS.CREATE_BLOG_POST,
    constant.ROUTING_URLS.EDIT_BLOG_POST,
    constant.ROUTING_URLS.VIEW_BLOG_POST,
  ],

  // Trip Management
  manageTrips: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.TRIPS_MAP,
    constant.ROUTING_URLS.VIEW_TRIPS,
    constant.ROUTING_URLS.NOTIFICATION,
    constant.ROUTING_URLS.VIEW_NOTIFICATION,
  ],

  // Bookings
  manageBookings: [
    constant.ROUTING_URLS.BOOKING,
    constant.ROUTING_URLS.CREATE_BOOKING,
    constant.ROUTING_URLS.VIEW_BOOKING,
  ],

  // Fleets
  manageFleets: [
    constant.ROUTING_URLS.FLEETS,
    constant.ROUTING_URLS.CREATE_FLEET,
    constant.ROUTING_URLS.EDIT_FLEET,
    constant.ROUTING_URLS.VIEW_FLEET,
  ],

  // Payments
  managePayments: [
    constant.ROUTING_URLS.PAYMENTS,
    constant.ROUTING_URLS.VIEW_PAYMENTS,
    constant.ROUTING_URLS.REFUND,
    constant.ROUTING_URLS.VIEW_REFUND,
    constant.ROUTING_URLS.REFUND_REQUEST,
  ],

  // Settings
  manageSettings: [
    constant.ROUTING_URLS.SETTINGS,
    constant.ROUTING_URLS.SITE_SETTINGS,
  ],

  manageIpAccess: [
    constant.ROUTING_URLS.IP_WHITE_LIST,
    constant.ROUTING_URLS.CREATE_IP_WHITE_LIST,
    constant.ROUTING_URLS.EDIT_IP_WHITE_LIST,
  ],

  manageRegionAdmins: [
    constant.ROUTING_URLS.REGION_ADMIN,
    constant.ROUTING_URLS.CREATE_REGION_ADMIN,
    constant.ROUTING_URLS.EDIT_REGION_ADMIN,
  ],

  manageDashboard: [constant.ROUTING_URLS.DASHBOARD],

  // Access All Features
  accessAllFeatures: [
    // This permission grants access to all routes
    ...Object.values(constant.ROUTING_URLS),
  ],
};

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  [constant.ROUTING_URLS.PARTNER]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_PARTNER]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_PARTNER]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_PARTNER]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.DASHBOARD]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
    ROLES.SEO,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.REPORTS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES]: [
    ROLES.ADMIN,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREW_MEMBERS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.CREATE_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.EDIT_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.VIEW_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.CHAUFFEUR]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
  ],
  [constant.ROUTING_URLS.CREATE_CHAUFFEUR]: [ROLES.PARTNER],
  [constant.ROUTING_URLS.EDIT_CHAUFFEUR]: [ROLES.PARTNER],
  [constant.ROUTING_URLS.VIEW_CHAUFFEUR]: [ROLES.PARTNER],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION_ADMIN]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.CREATE_REGION_ADMIN]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.EDIT_REGION_ADMIN]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.BOOKING]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.CREATE_BOOKING]: [ROLES.ADMIN, ROLES.PARTNER],
  // [constant.ROUTING_URLS.EDIT_BOOKING]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.USERS]: [ROLES.ADMIN, ROLES.REGIONAL_ADMIN],
  [constant.ROUTING_URLS.CREATE_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_USERS]: [ROLES.ADMIN, ROLES.REGIONAL_ADMIN],
  [constant.ROUTING_URLS.FLEETS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
  ],
  [constant.ROUTING_URLS.CREATE_FLEET]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.EDIT_FLEET]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.VIEW_FLEET]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.TRIPS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.TRIPS_MAP]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.VIEW_TRIPS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.PARTNER,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.NOTIFICATION]: [ROLES.ADMIN, ROLES.PARTNER, ROLES.SEO],
  [constant.ROUTING_URLS.VIEW_NOTIFICATION]: [
    ROLES.ADMIN,
    ROLES.PARTNER,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.PAYMENTS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.VIEW_PAYMENTS]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.REFUND]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.VIEW_REFUND]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.REFUND_REQUEST]: [ROLES.ADMIN, ROLES.PARTNER],
  [constant.ROUTING_URLS.SETTINGS]: [ROLES.ADMIN, ROLES.PARTNER, ROLES.SEO],
  [constant.ROUTING_URLS.SITE_SETTINGS]: [
    ROLES.ADMIN,
    ROLES.PARTNER,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.SEO]: [ROLES.ADMIN, ROLES.SEO],
};
