import { constant } from "@/lib/constant";

// roles.ts
export const ROLES = {
  ADMIN: "Super Admin",
  SEO: "SEO Agent",
  AFFILIATE: "Affiliate",
} as const;

// Permission to Route mapping - This maps backend permissions to frontend routes
export const PERMISSION_TO_ROUTE_MAPPING: Record<string, string[]> = {
  // User Management
  manageUsers: [
    constant.ROUTING_URLS.USERS,
    constant.ROUTING_URLS.CREATE_USERS,
    constant.ROUTING_URLS.EDIT_USERS,
    constant.ROUTING_URLS.VIEW_USERS,
  ],

  // Role Management
  manageRoles: [
    constant.ROUTING_URLS.STAFF_MEMBERS,
    constant.ROUTING_URLS.CREATE_STAFF_MEMBERS,
    constant.ROUTING_URLS.EDIT_STAFF_MEMBERS,
  ],

  // Permission Management
  managePermissions: [constant.ROUTING_URLS.SETTINGS],

  // Regional Management
  manageRegionAffiliates: [
    constant.ROUTING_URLS.AFFILIATE,
    constant.ROUTING_URLS.CREATE_AFFILIATE,
    constant.ROUTING_URLS.EDIT_AFFILIATE,
    constant.ROUTING_URLS.VIEW_AFFILIATE,
  ],

  manageRegionChauffeurs: [
    constant.ROUTING_URLS.CHAUFFEUR,
    constant.ROUTING_URLS.CREATE_CHAUFFEUR,
    constant.ROUTING_URLS.EDIT_CHAUFFEUR,
    constant.ROUTING_URLS.VIEW_CHAUFFEUR,
  ],

  setRegionPricing: [
    constant.ROUTING_URLS.REGION,
    constant.ROUTING_URLS.CREATE_REGION,
    constant.ROUTING_URLS.EDIT_REGION,
  ],

  viewRegionReports: [
    constant.ROUTING_URLS.REPORTS,
    constant.ROUTING_URLS.DASHBOARD,
  ],

  // Content Management
  optimizeContent: [
    constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES,
    constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT,
    constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT,
    constant.ROUTING_URLS.SEO,
    constant.ROUTING_URLS.NEWS,
    constant.ROUTING_URLS.CREATE_NEWS,
    constant.ROUTING_URLS.EDIT_NEWS,
    constant.ROUTING_URLS.FAQ,
    constant.ROUTING_URLS.CREATE_FAQ,
    constant.ROUTING_URLS.EDIT_FAQ,
    constant.ROUTING_URLS.TESTIMONIALS,
    constant.ROUTING_URLS.CREATE_TESTIMONIALS,
    constant.ROUTING_URLS.EDIT_TESTIMONIALS,
  ],

  manageSeoReports: [constant.ROUTING_URLS.SEO, constant.ROUTING_URLS.REPORTS],

  // Trip Management
  assignTrips: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.TRIPS_MAP,
    constant.ROUTING_URLS.VIEW_TRIPS,
  ],

  monitorLiveTrips: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.TRIPS_MAP,
    constant.ROUTING_URLS.VIEW_TRIPS,
  ],

  updateTripStatus: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.VIEW_TRIPS,
  ],

  handleTripEmergencies: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.NOTIFICATION,
    constant.ROUTING_URLS.VIEW_NOTIFICATION,
  ],

  // Chauffeur Management
  manageChauffeurs: [
    constant.ROUTING_URLS.DASHBOARD,
    constant.ROUTING_URLS.CHAUFFEUR,
    constant.ROUTING_URLS.CREATE_CHAUFFEUR,
    constant.ROUTING_URLS.EDIT_CHAUFFEUR,
    constant.ROUTING_URLS.VIEW_CHAUFFEUR,
  ],

  // Booking Management
  getRideList: [
    constant.ROUTING_URLS.BOOKING,
    constant.ROUTING_URLS.CREATE_BOOKING,
    // constant.ROUTING_URLS.EDIT_BOOKING,
    constant.ROUTING_URLS.VIEW_BOOKING,
  ],

  bookRide: [
    constant.ROUTING_URLS.BOOKING,
    constant.ROUTING_URLS.CREATE_BOOKING,
  ],

  // Fleet Management
  manageFleets: [
    constant.ROUTING_URLS.FLEETS,
    constant.ROUTING_URLS.CREATE_FLEET,
    constant.ROUTING_URLS.EDIT_FLEET,
    constant.ROUTING_URLS.VIEW_FLEET,
  ],

  // Crew Management
  manageCrew: [
    constant.ROUTING_URLS.CREW_MEMBERS,
    constant.ROUTING_URLS.CREATE_CREW_MEMBERS,
    constant.ROUTING_URLS.EDIT_CREW_MEMBERS,
    constant.ROUTING_URLS.VIEW_CREW_MEMBERS,
  ],

  // Payment Management
  managePayments: [
    constant.ROUTING_URLS.PAYMENTS,
    constant.ROUTING_URLS.VIEW_PAYMENTS,
    constant.ROUTING_URLS.REFUND,
    constant.ROUTING_URLS.VIEW_REFUND,
    constant.ROUTING_URLS.REFUND_REQUEST,
  ],

  // System Configuration
  configureSystem: [
    constant.ROUTING_URLS.SETTINGS,
    constant.ROUTING_URLS.IP_WHITE_LIST,
    constant.ROUTING_URLS.CREATE_IP_WHITE_LIST,
    constant.ROUTING_URLS.EDIT_IP_WHITE_LIST,
    constant.ROUTING_URLS.OUR_PARTNERS,
    constant.ROUTING_URLS.CREATE_OUR_PARTNERS,
    constant.ROUTING_URLS.EDIT_OUR_PARTNERS,
  ],

  // Regional Admin Management
  manageRegionalAdmins: [
    constant.ROUTING_URLS.REGION_ADMIN,
    constant.ROUTING_URLS.CREATE_REGION_ADMIN,
    constant.ROUTING_URLS.EDIT_REGION_ADMIN,
  ],

  // View All Regions
  viewAllRegions: [
    constant.ROUTING_URLS.DASHBOARD,
    constant.ROUTING_URLS.REGION,
    constant.ROUTING_URLS.CREATE_REGION,
    constant.ROUTING_URLS.EDIT_REGION,
  ],

  // Access All Features
  accessAllFeatures: [
    // This permission grants access to all routes
    ...Object.values(constant.ROUTING_URLS),
  ],
};

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  [constant.ROUTING_URLS.AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.DASHBOARD]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.REPORTS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES]: [
    ROLES.ADMIN,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CHAUFFEUR]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_CHAUFFEUR]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_CHAUFFEUR]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_CHAUFFEUR]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  // [constant.ROUTING_URLS.EDIT_BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.FLEETS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.TRIPS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.TRIPS_MAP]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_TRIPS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.NOTIFICATION]: [
    ROLES.ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.VIEW_NOTIFICATION]: [
    ROLES.ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.PAYMENTS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_PAYMENTS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.REFUND]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_REFUND]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.REFUND_REQUEST]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.SETTINGS]: [ROLES.ADMIN, ROLES.AFFILIATE, ROLES.SEO],
  [constant.ROUTING_URLS.SEO]: [ROLES.ADMIN, ROLES.SEO],
};
