import { constant } from "@/lib/constant";

// roles.ts
export const ROLES = {
  ADMIN: "Super Admin",
  REGIONAL_ADMIN: "Regional Admin",
  SEO: "SEO Agent",
  AFFILIATE: "Affiliate",
  DISPATCHER: "Dispatcher",
} as const;

// Permission to Route mapping - This maps backend permissions to frontend routes
export const PERMISSION_TO_ROUTE_MAPPING: Record<string, string[]> = {
  // User Management
  Users: [
    constant.ROUTING_URLS.USERS,
    constant.ROUTING_URLS.CREATE_USERS,
    constant.ROUTING_URLS.EDIT_USERS,
    constant.ROUTING_URLS.VIEW_USERS,
  ],

  // Staff Management (replaces manageRoles)
  "Staff Members": [
    constant.ROUTING_URLS.STAFF_MEMBERS,
    constant.ROUTING_URLS.CREATE_STAFF_MEMBERS,
    constant.ROUTING_URLS.EDIT_STAFF_MEMBERS,
  ],

  // Permission Management
  "Permission Management": [constant.ROUTING_URLS.SETTINGS],

  // Regional Management
  Affiliates: [
    constant.ROUTING_URLS.AFFILIATE,
    constant.ROUTING_URLS.CREATE_AFFILIATE,
    constant.ROUTING_URLS.EDIT_AFFILIATE,
    constant.ROUTING_URLS.VIEW_AFFILIATE,
  ],

  Chauffeurs: [
    constant.ROUTING_URLS.CHAUFFEUR,
    constant.ROUTING_URLS.CREATE_CHAUFFEUR,
    constant.ROUTING_URLS.EDIT_CHAUFFEUR,
    constant.ROUTING_URLS.VIEW_CHAUFFEUR,
  ],

  Regions: [
    constant.ROUTING_URLS.REGION,
    constant.ROUTING_URLS.CREATE_REGION,
    constant.ROUTING_URLS.EDIT_REGION,
  ],

  Reports: [constant.ROUTING_URLS.REPORTS, constant.ROUTING_URLS.DASHBOARD],

  // Content Management
  "Content Management": [
    constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES,
    constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT,
    constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT,
  ],

  SEO: [constant.ROUTING_URLS.SEO, constant.ROUTING_URLS.REPORTS],

  News: [
    constant.ROUTING_URLS.NEWS,
    constant.ROUTING_URLS.CREATE_NEWS,
    constant.ROUTING_URLS.EDIT_NEWS,
  ],

  FAQs: [
    constant.ROUTING_URLS.FAQ,
    constant.ROUTING_URLS.CREATE_FAQ,
    constant.ROUTING_URLS.EDIT_FAQ,
  ],

  Testimonials: [
    constant.ROUTING_URLS.TESTIMONIALS,
    constant.ROUTING_URLS.CREATE_TESTIMONIALS,
    constant.ROUTING_URLS.EDIT_TESTIMONIALS,
  ],

  "Blog Posts": [
    constant.ROUTING_URLS.BLOG_POSTS,
    constant.ROUTING_URLS.CREATE_BLOG_POST,
    constant.ROUTING_URLS.EDIT_BLOG_POST,
    constant.ROUTING_URLS.VIEW_BLOG_POST,
  ],

  // Trip Management
  Trips: [
    constant.ROUTING_URLS.TRIPS,
    constant.ROUTING_URLS.TRIPS_MAP,
    constant.ROUTING_URLS.VIEW_TRIPS,
    constant.ROUTING_URLS.NOTIFICATION,
    constant.ROUTING_URLS.VIEW_NOTIFICATION,
  ],

  // Bookings
  Bookings: [
    constant.ROUTING_URLS.BOOKING,
    constant.ROUTING_URLS.CREATE_BOOKING,
    constant.ROUTING_URLS.VIEW_BOOKING,
  ],

  // Fleets
  Fleets: [
    constant.ROUTING_URLS.FLEETS,
    constant.ROUTING_URLS.CREATE_FLEET,
    constant.ROUTING_URLS.EDIT_FLEET,
    constant.ROUTING_URLS.VIEW_FLEET,
  ],

  // Payments
  Payments: [
    constant.ROUTING_URLS.PAYMENTS,
    constant.ROUTING_URLS.VIEW_PAYMENTS,
    constant.ROUTING_URLS.REFUND,
    constant.ROUTING_URLS.VIEW_REFUND,
    constant.ROUTING_URLS.REFUND_REQUEST,
  ],

  // Settings
  Settings: [constant.ROUTING_URLS.SETTINGS],

  "IP Whitelist": [
    constant.ROUTING_URLS.IP_WHITE_LIST,
    constant.ROUTING_URLS.CREATE_IP_WHITE_LIST,
    constant.ROUTING_URLS.EDIT_IP_WHITE_LIST,
  ],

  "Our Partners": [
    constant.ROUTING_URLS.OUR_PARTNERS,
    constant.ROUTING_URLS.CREATE_OUR_PARTNERS,
    constant.ROUTING_URLS.EDIT_OUR_PARTNERS,
  ],

  "Region Admins": [
    constant.ROUTING_URLS.REGION_ADMIN,
    constant.ROUTING_URLS.CREATE_REGION_ADMIN,
    constant.ROUTING_URLS.EDIT_REGION_ADMIN,
  ],

  // Access All Features
  accessAllFeatures: [
    // This permission grants access to all routes
    ...Object.values(constant.ROUTING_URLS),
  ],
};

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  [constant.ROUTING_URLS.AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_AFFILIATE]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.DASHBOARD]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.REPORTS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.CONTENT_MANAGEMENT_ALL_PAGES]: [
    ROLES.ADMIN,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.CREATE_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_CONTENT_MANAGEMENT]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_CREW_MEMBERS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CHAUFFEUR]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
  ],
  [constant.ROUTING_URLS.CREATE_CHAUFFEUR]: [ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_CHAUFFEUR]: [ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_CHAUFFEUR]: [ROLES.AFFILIATE],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_STAFF_MEMBERS]: [ROLES.ADMIN, ROLES.ADMIN],
  [constant.ROUTING_URLS.NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_NEWS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_FAQ]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.CREATE_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.EDIT_TESTIMONIALS]: [ROLES.ADMIN, ROLES.SEO],
  [constant.ROUTING_URLS.IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_IP_WHITE_LIST]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_OUR_PARTNERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.CREATE_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_REGION]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_REGION_ADMIN]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.CREATE_BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  // [constant.ROUTING_URLS.EDIT_BOOKING]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.USERS]: [ROLES.ADMIN, ROLES.REGIONAL_ADMIN],
  [constant.ROUTING_URLS.CREATE_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.EDIT_USERS]: [ROLES.ADMIN],
  [constant.ROUTING_URLS.VIEW_USERS]: [ROLES.ADMIN, ROLES.REGIONAL_ADMIN],
  [constant.ROUTING_URLS.FLEETS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
  ],
  [constant.ROUTING_URLS.CREATE_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.EDIT_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_FLEET]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.TRIPS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.TRIPS_MAP]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.VIEW_TRIPS]: [
    ROLES.ADMIN,
    ROLES.REGIONAL_ADMIN,
    ROLES.AFFILIATE,
    ROLES.DISPATCHER,
  ],
  [constant.ROUTING_URLS.NOTIFICATION]: [
    ROLES.ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.VIEW_NOTIFICATION]: [
    ROLES.ADMIN,
    ROLES.AFFILIATE,
    ROLES.SEO,
  ],
  [constant.ROUTING_URLS.PAYMENTS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_PAYMENTS]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.REFUND]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.VIEW_REFUND]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.REFUND_REQUEST]: [ROLES.ADMIN, ROLES.AFFILIATE],
  [constant.ROUTING_URLS.SETTINGS]: [ROLES.ADMIN, ROLES.AFFILIATE, ROLES.SEO],
  [constant.ROUTING_URLS.SEO]: [ROLES.ADMIN, ROLES.SEO],
};
